name: Imgame backend sandbox

on:
  schedule:
    - cron:  '5 2-16 * * *'

jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Create cache directory
        run: |
          mkdir -p .cache

      - name: Cache composer cache
        uses: actions/cache@v2
        with:
          path: .cache
          key: auctioner-file-cache

      - name: Run scan
        run: |
          ./wow-auctioneer scan --server "Argent Dawn" -t
