name: Auctioneer scheduled scan

#on:
#  schedule:
#    - cron: '0 2-16 * * *'

jobs:
  run-scan:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Create cache directory
        run: |
          mkdir -p .cache

      - name: Cache
        uses: actions/cache@v2
        with:
          path: .cache
          key: auctioner-file-cache

      - name: Run scan
        env:
          AUCTIONEER_BLIZZARD_CLIENT_SECRET: '${{ secrets.BLIZZARD_CLIENT_SECRET }}'
          AUCTIONEER_BLIZZARD_CLIENT_ID: '${{ secrets.BLIZZARD_CLIENT_ID }}'
          AUCTIONEER_TELEGRAM_TOKEN: '${{ secrets.TELEGRAM_TOKEN }}'
          AUCTIONEER_TELEGRAM_CHAT_ID: '${{ secrets.TELEGRAM_CHAT_ID }}'
        run: |
          ./wow-auctioneer scan --server "Argent Dawn" --fromIlvl 430 --toIlvl 490 --minBuyout 300000000 -t
